version: 2.1
orbs:
  matlab: mathworks/matlab@0.1
  codecov: codecov/codecov@1.0.2

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - matlab/install
      - matlab/run-tests:
          test-results-junit: test-results/results.xml
          code-coverage-cobertura: code-coverage/coverage.xml
          source-folder: tbx
      - store_test_results:
          path: test-results
      - store_artifacts: 
          path: code-coverage
      - codecov/upload:
          file: code-coverage/coverage.xml